/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CenterPlane: typeof import('./src/components/plane/centerPlane.vue')['default']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    LeftPlane: typeof import('./src/components/plane/leftPlane.vue')['default']
    MultiButton: typeof import('./src/components/MultiButton/index.vue')['default']
    RightPlane: typeof import('./src/components/plane/rightPlane.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
