/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardCom: typeof import('./src/components/cardCom/index.vue')['default']
    CenterPlane: typeof import('./src/components/plane/centerPlane.vue')['default']
    Children: typeof import('./src/components/MultiButton/children.vue')['default']
    CustomTable: typeof import('./src/components/customTable/customTable.vue')['default']
    CustomTable2: typeof import('./src/components/customTable/customTable2.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    LayerItem: typeof import('./src/components/MultiButton/LayerItem.vue')['default']
    LeftPlane: typeof import('./src/components/plane/leftPlane.vue')['default']
    MultiButton: typeof import('./src/components/MultiButton/index.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader/index.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    RightPlane: typeof import('./src/components/plane/rightPlane.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
